name: docgen from Jira
on:
  workflow_dispatch

jobs:
   generate:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for metadata
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install "lander<2.0.0"

      - name: condaenv
        run: |
          conda init bash
          conda create --name docsteady-env docsteady -c lsst-dm -c conda-forge
        shell: bash

      - name: docugen
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        run: |
          source ${CONDA}/bin/activate docsteady-env
          docsteady --namespace PSE generate-tpr LVV-P63 SCTR-14.tex
          echo `ls -la SCTR-14.tex`
        shell: bash
 
      - name: Create commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit --allow-empty -m "Update from JIRA " SCTR-14.tex 


      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'

      - name: Landing page upload
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --upload --pdf SCTR-14.pdf --lsstdoc SCTR-14.tex --ltd-product sctr-14
