name: docgen from Jira
on:
  workflow_dispatch

jobs:
   generate:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for metadata
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install "lander<2.0.0"

      - name: condaenv
        run: |
          conda init bash
          conda create --name docsteady-env docsteady -c lsst-dm -c conda-forge
        shell: bash

      - name: docugen
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        run: |
          conda info --envs
          source ${CONDA}/bin/activate docsteady-env
          docsteady  generate-tpr LVV-P63 SCTR-14.tex
        shell: bash
 
      - name: Upload resulting document as artifact
        uses: actions/upload-artifact@v2
        with:
          name: SCTR-14.tex
          path: ./sctr-14/SCTC-14.tex


